### ISSUE TITLE
Applicative composition

### ISSUE THREAD

**Issue by eulerfx** [palladin/Higher#5]
Given `Applicative<'F>` and `Applicative<'G>`, I would like to implement their composite. I'm not sure how to proceed given the new `Compose` instance. I've done it with a different instance of `Compose` as follows:

```fsharp

type Comp<'F, 'G> = App2<Comp, 'F, 'G>

and Comp private () =
  static let token = new Comp ()
  static member Inj (value:App<'F, App<'G, 'A>>) : App<Comp<'F, 'G>, 'A> =
    let app = App<_, _>(token, value)
    let app2 = App2<_, _, _>(AppToken<Comp, 'F>.Token token, app)
    let token2 : App<Comp, 'F> = AppToken<Comp, 'F>.Token token
    App3<_, _, _, _>(AppToken<App<Comp, 'F>, 'G>.Token token2, app2)  
  static member Prj (app3:App<Comp<'F, 'G>, 'A>) : App<'F, App<'G, 'A>> =
    let t = AppToken<Comp, 'F>.Token token
    let t1 : App2<Comp, 'F, 'G> = AppToken<_, _>.Token t
    let app2 : App2<Comp, 'F, 'G> = app3.Apply t1 :?> _
    let app : App<Comp, 'F> = app2.Apply t :?> _
    app.Apply token :?> _

module Applicative =
  
  let compose (F:Applicative<'F>) (G:Applicative<'G>) : Applicative<Comp<'F, 'G>> =    
    { new Applicative<_>() with
        member x.Pure<'A> (a:'A) : App<Comp<'F, 'G>, 'A> = 
          let a = F.Pure (G.Pure a)
          Comp.Inj a
        member x.Apply (f:App<Comp<'F, 'G>, 'A -> 'B>) (fa:App<Comp<'F, 'G>, 'A>) : App<Comp<'F, 'G>, 'B> = 
          let f' = Comp.Prj f
          let fa' = Comp.Prj fa
          F.Apply (F.Map (G.Apply) f') fa' |> Comp.Inj }
```

Thoughts?

**Comment by eulerfx** [comment]
FWIW, `Monad` and `Comonad` instances for `Adjunction` looked like this: 

```fsharp
module Adjunction = 

  let monad (adj:Adjunction<'G, 'F>) (F:Functor<'F>) (G:Functor<'G>) : Monad<Comp<'F, 'G>> =
    { new Monad<_>() with
        member __.Return<'A> (a:'A) : App<Comp<'F, 'G>, 'A> =
          adj.Unit a |> Comp.Inj
        member __.Bind<'A, 'B> (a:App<Comp<'F, 'G>, 'A>, f:'A -> App<Comp<'F, 'G>, 'B>) : App<Comp<'F, 'G>, 'B> =
          F.Map (adj.RightAdjunct G (f >> Comp.Prj)) (Comp.Prj a) |> Comp.Inj }

  let comonad (adj:Adjunction<'F, 'G>) (F:Functor<'F>) (G:Functor<'G>) : Comonad<Comp<'F, 'G>> =
    { new Comonad<_>() with
        member __.Extract<'A> (w:App<Comp<'F, 'G>, 'A>) : 'A =
          adj.CoUnit (Comp.Prj w)
        member __.Extend<'A, 'B> (f:App<Comp<'F, 'G>, 'A> -> 'B) (w:App<Comp<'F, 'G>, 'A>) : App<Comp<'F, 'G>, 'B> =
          F.Map (adj.LeftAdjunct G (Comp.Inj >> f)) (Comp.Prj w) |> Comp.Inj }
```

**Comment by palladin** [comment]
Hi Lev,
The correct Haskell type is 
``newtype Compose f g a = Comp { unComp :: f (g a) }`` 
with kind (* -> *) -> (* -> *) -> * -> *

So you can implement Applicative composition like 
https://github.com/palladin/Higher/commit/ae0395350d9e3d0a4e4f3426675925fe7b2bf78e

**Comment by palladin** [comment]
Check also 
https://www.cl.cam.ac.uk/~jdy22/papers/lightweight-higher-kinded-polymorphism.pdf
``
The obvious disadvantage to the lack of a kind system is that the type
checker is no help in preventing the formation of ill-kinded expressions, such
as (List.t, List.t) app. However, this drawback is not so serious as might first
appear, since it does not introduce any means of forming ill-typed values, and
so cannot lead to runtime errors. 
``

**Comment by eulerfx** [comment]
Ah, in fact the two definitions of `Compose` here are equivalent except for the explicit `Compose` constructor you used. Any thoughts on when to use an explicit constructor and when not to?

**Comment by palladin** [comment]
The definition of ``type Comp<'F, 'G> = App2<Comp, 'F, 'G>`` is in a sense ill-typed... because you appy Comp to 'A like App<App<'F, 'G>, 'A> is of kind ``(* -> * -> *) -> * -> * -> *`` and as I said the proper Compose type is of kind ``(* -> *) -> (* -> *) -> * -> *``

**Comment by eulerfx** [comment]
If you example the types (eyeballing) you get:

`fsharp
val Inj : App<'F, App<'G, 'A>> -> App3<Comp, 'F, 'G, 'A>
val Prj : App3<Comp, 'F, 'G, 'A> -> App<'F, App<'G, 'A>> 
`

**Comment by palladin** [comment]
hmm... sorry your type is in a sense is a partial application of Compose

**Comment by eulerfx** [comment]
:)

I wonder where Higher is on this scale:
 
![image](https://cloud.githubusercontent.com/assets/609910/16916725/61608972-4ccc-11e6-82f9-b4a6d11b205f.png)

**Comment by palladin** [comment]
:)
One interesting concept is that with LHKT you can have "poly" kinded definitions. So we need to be careful and check when the forall of F# generics act as a forall quantifier at the kind level.

**Comment by eulerfx** [comment]
Yeah this is what I've struggled with.

**Comment by palladin** [comment]
:) Yes, I got confused too.
