### ISSUE TITLE
Should Codensity be instance of Ran?

### ISSUE THREAD

**Issue by eulerfx** [palladin/Higher#7]
Its there in the comments for `Ran`, but should `Codensity` be:

```fsharp
type Codensity<'M, 'A> = Ran<'M, 'M, 'A>
```

**Comment by palladin** [comment]
All Concepts are Kan Extensions :)
For Codensity and Yoneda I like the implementations to be explicit.

**Comment by eulerfx** [comment]
Cool. I'll dig up a sample of actually using codensity to optimize a bind.
